# Generated by Django 5.2.5 on 2025-09-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.TextField(help_text='Encrypted message payload (base64 or hex string)')),
                ('encryption_algo', models.CharField(default='ai_hybrid', help_text='Algorithm used for encryption (e.g., Fernet, AES, RSA)', max_length=100)),
                ('key_metadata', models.TextField(blank=True, help_text='Optional key ID or encrypted key. ⚠️ Do not store raw keys in plaintext.')),
                ('hash_value', models.CharField(help_text='SHA-256 or similar hash of the original plaintext', max_length=256)),
                ('is_read', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False, help_text='True once notification/email has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
