# Generated by Django 5.2.5 on 2025-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classification',
            field=models.CharField(default='normal', help_text='Sensitivity level (low, medium, high)', max_length=50),
        ),
    ]
