# Generated by Django 5.2.5 on 2025-09-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='key_metadata',
        ),
        migrations.AddField(
            model_name='message',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='classification',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='encryption_algo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
