# Generated by Django 5.2.5 on 2025-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_options_remove_message_key_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encryption_algo',
        ),
        migrations.AlterField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
    ]
