# Generated by Django 5.2.5 on 2025-09-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_message_encryption_algo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='classification',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='hash_value',
            field=models.CharField(blank=True, help_text='Optional SHA-256 hash', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='private_key',
            field=models.TextField(blank=True, help_text='AES key for medium / RSA private key for high', null=True),
        ),
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.message')),
            ],
        ),
    ]
