# Generated by Django 5.2.5 on 2025-10-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_message_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=10),
        ),
    ]
